[package]
name = "tcp-server"
version = "0.1.0"
edition = "2021"

[features]
sql = []

[dependencies]
url = "2.5.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.14"
chrono = "0.4.4"
rusqlite = { version = "0.36", features = ["bundled"] }
toml = "0.8.2"
